[build-system]
requires = ["poetry>=1.8.5"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"

[tool.poetry.group.dev.dependencies]
pytest = "*"
flake8 = "*"
mypy = "*"
isort = "*"
black = "*"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]

[tool.isort]
profile = "black"

[tool.mypy]
strict = true
ignore_missing_imports = true
exclude = [".venv"]

[tool.black]
line-length = 120
