[build-system]
requires = ["poetry>=2.1.3"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.13.3"
azure-identity = "^1.23.0"
openai = "^1.82.0"
python-dotenv = "^1.1.0"
pyaudio = "^0.2.14"
audioop-lts = "^0.2.1"
google-cloud-aiplatform = "^1.94.0"
google-auth = "^2.40.2"
webrtcvad = "^2.0.10"
setuptools = "^80.9.0"
google-cloud-speech = "^2.32.0"
google-cloud-texttospeech = "^2.27.0"

[tool.poetry.group.dev.dependencies]
pytest = "8.3.5"
mypy = "1.15.0"
isort = "6.0.1"

no-print-checker = { path = "./plugins/no_print_checker", develop = true }
faker = "37.3.0"
ruff = "^0.11.12"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]

[tool.mypy]
strict = true
ignore_missing_imports = true
exclude = [".venv"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["ALL"]
ignore = ["D100", "D104", "COM812"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["D100", "D101", "D102", "D103", "D104", "D107"]
