name: Setup python
description: Setup python

runs:
  using: composite
  steps:
    - id: get-python-version
      shell: bash
      run: |
        python_version="$(grep '^python\s*=\s*' pyproject.toml | grep -Eo '[0-9]+\.[0-9]+(\.[0-9]+)?')"
        echo "python-version=${python_version}" >> "$GITHUB_OUTPUT"
    - uses: actions/setup-python@v5.6.0
      with:
        python-version: ${{ steps.get-python-version.outputs.python-version }}
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get install portaudio19-dev
        pip install poetry
        poetry install --no-root
